### ISSUE TITLE
Rendered FX2D not working

### ISSUE THREAD

**Issue by MatthijsHoekstra** [leadedge/SpoutProcessing#2]
Will there be in the future any support for FX2D within Spout for Processing?

**Comment by leadedge** [comment]
I have not investigated this. The main thing has been to maintain the library to keep it updated.

I will make some preliminary investigation, but at the moment it is not on the radar.

**Comment by MatthijsHoekstra** [comment]
Thanks for the comment! I was wondering if it is hard to implement? I did some investigation into the code of the libary and couldn't find a way myself. As I am working an interactive light installation, frames per second need to be as high as possible, as you maybe know FX2D has a pretty big improvement in fps. I hope it will be implemented, but don't want to pressure you.

**Comment by leadedge** [comment]
I had a brief look and see that it would involve the using required libraries in Eclipse, JavaFX I believe. I would have to sit down to it and find out what to do even before starting to change the library. I have several other projects on the go so can't commit to it right now but will keep it in mind.

**Comment by MatthijsHoekstra** [comment]
Hi Lead, wondering if there is any possibility if this would be a possibility?

**Comment by leadedge** [comment]
Sorry I have not been able to investigate fully so I can't say. It's too much of a project on it's own and I don't have time to commit to it right now.
