### ISSUE TITLE
Not opening processing Sketch

### ISSUE THREAD

**Issue by ThomasLengeling** [leadedge/SpoutProcessing#4]
Hello,

I am not sure if I am missing something, I run the processing sketch and no window is opening or nothing is displayed on the console. Here is what I did.
 I installed Spout from the website on my machine windows 10 64 bits.
I installed Spout for processing from the libraries manager.
The I run one example and there is windows creating, and cannot see any receiving texture.
I tested on openfremeworks and Spout works perfect, but I am having trouble in processing.

Thank for the help.

**Comment by ThomasLengeling** [comment]
in the task manager the process joamp_exe_ts.exe is hanging, if I end the task the window is created but with an error, any suggestions?

**Comment by leadedge** [comment]
The first thing I always ask is whether this is a laptop with Optimus graphics. Spout might run fine for some programs but not for others. Then check system compatibility using Help > Diagnostics with the Spout demo sender so we know something about the system.

Because jogamp is hanging, I think it is most likely a problem with Java. Similar problems have been reported :

https://github.com/processing/processing/issues/4239

I have found problems with anti virus programs :

https://github.com/processing/processing/issues/4104#issuecomment-159802341

I would start by commenting out lines of code until the sketch works and try to narrow it down. For example it could be due to loading the Spout library itself or some function in the library.

**Comment by ThomasLengeling** [comment]
Yes, you are right, it is not the spout program, a simple P3D example won't run.

I also deactivate windowss defender and windows virus scanner.

For example, If I run the Planets example in Demo/Graphics the program hangs. But once I end the joamp.exe task in the task manager the app opens without a problem.

If I do the same thing with spoutSender example I get his error manage, do you think it is trying to find the .dll files in the temporary local folder that the joamp.exe is being created?

````
Spout 64bit v2.0.6.0 - Java 1.8.0_162
sendTexture
Created sender 'SpoutSender' (640x360)
java.lang.UnsatisfiedLinkError: spout.JNISpout.getShareMode(J)I
	at processing.opengl.PSurfaceJOGL$2.run(PSurfaceJOGL.java:408)
	at java.lang.Thread.run(Thread.java:748)
A library relies on native code that's not available.
Or only works properly when the sketch is run as a 32-bit application.
````

**Comment by leadedge** [comment]
OK - it looks like the anti-virus possibility is eliminated.

`"Or only works properly when the sketch is run as a 32-bit application"`

I have seen this before, and it does not necessarily mean what it says. The library should detect if the system is 32bit or 64bit when it loads and it is indeed reporting 64bit. So I don't think this is the problem, especially if you have to end jogamp to make anything work.

I think you should concentrate on the main problem that a simple P3D sketch does not run. Is it related to P3D, P2D or no specification at all? If you can isolate this to something repeatable and separate from the Spout library, it is definitely worth submitting a problem report on the Processing GitHub issues.

**Comment by ThomasLengeling** [comment]
I found the problem. I have this mapping software https://fly.elise-ng.net/ installed on my Windows and its causing conflict with Processing joamp executable.  I am not sure why but when I uninstalled the the software processing/joamp/spout works as expected. 
Thank you for your help.

**Comment by leadedge** [comment]
It's good that you found it, but not so good that you have to un-install something and we don't know why. Maybe a Java version conflict at a guess.
