### ISSUE TITLE
Function ReceivePixels is missing

### ISSUE THREAD

**Issue by phils93** [leadedge/SpoutProcessing#7]
Hello i am using a software that uses Spout and in his code he is using ReceivePixels function from Spout, did that function got deleted ? and if yes why ? and is there any alternative to it ? thank you very much

**Comment by leadedge** [comment]
This is a function in the Processing JNI library. So it must have something to do with Processing, unless he is using the library directly somehow. It goes back to 2016 so I can't say when it was used or not. 

As it happens, I am revising the Processing library at the moment in response to [this issue](https://spout.discourse.group/t/read-pixel-color-in-processing/378).

In that post I have given a link to an example with a simple workaround which the user reports as OK. I intend to include this in the next release of the Processing library.

This will work if you are using Processing. But in any event it will help if you can provide  more details of what software you are referring to.

**Comment by leadedge** [comment]
I found the function in archived backups and it does date back to 2016.  I don't know why it was removed. Perhaps there were problems with the image texture. I will investigate while I am revising the library. Meanwhile use the workaround sketch.

**Comment by phils93** [comment]
thank you very much and i till then i will try use to use the workaround sketch just let me know if this function will be integrated again or not ?

**Comment by leadedge** [comment]
Sorry for the post edit, but I first mis-understood.

To make it clear, the old "ReceivePixels" has problems, but the new method will be integrated.

Most likely I will add a new function "ReceiveImage" so that existing applications are not affected. Please let me know if you have any trouble with this method. It is identical to that used by Syphon.

**Comment by phils93** [comment]
no i think it goes well with me as i have only to replace ReceivePixels

**Comment by leadedge** [comment]
We seem to have cross-posted. You will  replace ReceivePixels with ReceiveImage but it will take a while to update the library. Meanwhile the workaround should work for you.

**Comment by leadedge** [comment]
Updated [2.0.7.3](https://github.com/leadedge/SpoutProcessing/releases/tag/latest)
It will take a while for it to show up in the Processing Library Manager.
