### ISSUE TITLE
UnsatisfiedLinkError JNISpout.init()

### ISSUE THREAD

**Issue by b-s-l-s-k** [leadedge/SpoutProcessing#8]
I am trying to add Spout support to my java application. I have added the core.jar file to my library, everything complies fine.

When I ran the program with the addition of Spout, it gave my the UnsatifiedLinkError, saying it cannot find the JNISpout_64 

I fixed this issue by adding the JNISpout_64 and _32 to my library as well. Now when the program runs, it is the same error, but with a different message:

`Exception in thread "Thread-0" java.lang.UnsatisfiedLinkError: 'long com.bslsk.io.JNISpout.init()'
	at com.bslsk.io.JNISpout.init(Native Method)
	at com.bslsk.io.Spout.<init>(Spout.java:182)
	at com.bslsk.bin.GFrame.<init>(GFrame.java:157)
	at com.bslsk.bin.SplashScreen.run(SplashScreen.java:64)
	at java.base/java.lang.Thread.run(Thread.java:1583)
`

FOR CONTEXT: 
I am making a Visual Jockey application in java, and I would like to send the frames as a BufferedImage -> PImage through Spout as a sender, and another application is the receiver. 

Included in my app is the Spout.java and JNISPout.java files from the repo. 

I have no idea what I'm doing wrong and have checked other closed issue threads, but nothing works thus far.

**Comment by b-s-l-s-k** [comment]
UPDATE:
after doing a bunch of random edits, what finally worked is putting Spout and JNISpout into their own package called "spout" 

NEW problem: 

`Exception in thread "Thread-1" java.lang.NullPointerException: Cannot read field "glWidth" because "tex" is null
	at spout.Spout.sendTexture(Spout.java:410)
	at com.bslsk.bin.GFrame.run(GFrame.java:229)
	at java.base/java.lang.Thread.run(Thread.java:1583)
`

I put a 'System.out.println(img..toString())'
img is not null with output 'processing.core.PImage@7e085a15'

but the next call to 'Texture tex = pgl.getTexture(img);'

throws the error.

**Comment by leadedge** [comment]
This is going back a while now but I seem to recall that "getTexture" was not an "approved" function. I found it [here](https://processing.github.io/processing-javadocs/core/processing/opengl/PGraphicsOpenGL.html). 

"getTexture() - Not an approved function, this will change or be removed in the future."

Can you try using "sendTexture(PGraphics pgr)" or "sendTexture(PImage img)"

Edit

My mistake - I see you are already using Pimage. Anyway try a graphics object to see if you get the same error. If it's common to both it tells something at least.
Also GetTexture(Pimage) is also not "approved".

Edit 2

I don't know how it would fit with your application, but in a Processing sketch it is necessary to use the "size" function before using PGraphics.

**Comment by b-s-l-s-k** [comment]
At the very least I was able to get past another error and now I'm stuck on a new and even more strange error:
`Image width and height cannot be larger than 0 with this graphics card.`

For reference I have an Nvidia GTX 1050 discrete card + an Intel integrated Graphics

Online the only other thing I could find of a similar error is a much more complicated endeavor, but the person doesn't have the same issue. In that forum post [https://forum.processing.org/two/discussion/18838/error-java-lang-runtimeexception-image-width-and-height-cannot-be-larger-than.html](url) 
The "limit" set by processing is 4096, while mine is zero. 

Even with that, a sender was created and initialized, yet no receiver can find it? Im not sure if that's because there is nothing to "Stream", but I think it should still show up at the very least since it was initialized.

**Comment by leadedge** [comment]
If this is a laptop you have to be careful that the 1050 is being used in favour of the Intel one. You have to check both NVIDIA and Windows settings. "SpoutSettings" has help buttons to explain. If it's a desktop it should have no effect but it's safe to do the same thing.

 You probably have to use "setSenderName("Sender name")" if it is not a Processing sketch.

To avoid the possibility that the error is closing the sender somehow, leave out "SendTexture". The sender should still show up in the sender list for "SpoutPanel" that pops up with right click for the Spout Demo Receiver.

**Comment by b-s-l-s-k** [comment]
I had already run the SpoutSettings, as well as tested the Send/Receive Demos, which worked fine. 
I get the following Debug Output when running my program: 

`Spout 64bit v2.0.7.8 - Java 21.0.1
processing.opengl.PGraphicsOpenGL@2f943d71
processing.opengl.PGraphicsOpenGL@2f943d71
Created sender 'MELTr' (960x540)
Spout initialized texture sharing`

Which shows that the sender is being created and properly initialized, yet it doesn't show up in any Receiver program. 

I have created a subclass of PApplet called XApplet, which initializes, but I continue to run into tons of errors relating to Processing failing to create a valid GL instance. 

`java.lang.NullPointerException: Cannot invoke "com.jogamp.opengl.GL.glGetError()" because "this.gl" is null
	at processing.opengl.PJOGL.getError(PJOGL.java:1129)
	at processing.opengl.PGraphicsOpenGL.report(PGraphicsOpenGL.java:5310)
	at processing.opengl.PGraphicsOpenGL.endDraw(PGraphicsOpenGL.java:1441)
	at processing.core.PApplet.handleDraw(PApplet.java:2111)
	at processing.awt.PSurfaceAWT$9.callDraw(PSurfaceAWT.java:1386)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:356)
`

Every time I feel like I get a step closer to this working, it spits out tons of errors that are internal and not editable by me.

**Comment by leadedge** [comment]
At least this confirms that there is no GL context. As mentioned above if "Size" is not used in the sketch the console shows "RuntimeException: createGraphics()". Also I believe you you need to specifically enable P3D. Each demo sketch has -

`size(640, 360, P3D);`

Also you might find something from Spout error logs -

`enableSpoutLogFile(String filename)`

If the name is not a full path, the log file is saved in -

"C:>Users>username>AppData>Roaming>Spout"

When you say the sender does not show up, is it missing from the sender list in the demo receiver, or is it a black screen?

**Comment by b-s-l-s-k** [comment]
I have been testing out dozens of possible configurations to get it to work, but I have used
`size(640, 360, P3D);`
or more specifically 
`size(640, 360, PConstants.P3D);` 

If I do that, it says "this.g" is null
if I create a PGraphics, it says "tex is null"
In the cases where tex is NOT null, tex.glWidth is 0, and the JNISpout throws the error. 

In the receiver demo, it is a black screen that says "no sender detected", even when it does initialize. 

Do you happen to have a working Java example that utilizes this that I could try?

**Comment by leadedge** [comment]
It looks like the size function itself needs a GL context. Create a Spout log file. This should show the cause and narrow down the error.

Sorry I don't have a Java example. SpoutProcessing is a collaborative project and the JNI library was made open so that the Processing library could be re-created if necessary.

**Comment by leadedge** [comment]
I found a mistake in the JNISpout library which uses the Spout source files. The "CheckSender" function in "Spout.cpp" which creates a new sender was not returning false if the DirectX and OpenGL setup failed. The changed file "Spout.cpp" is in the SpoutGL folder of the [JNISpout repository](https://github.com/leadedge/JSpoutLIB/tree/main/SpoutGL). This might explain why the sender was apparently created successfully. Either the DirectX or OpenGL setup could have failed resulting in a null context . The log file will show any errors.

**Comment by b-s-l-s-k** [comment]
I finally figured out the problems. I was trying at first to make a PApplet, PGraphics, and PImage inside of a JFrame, then use the frame's thread to call 'repaint()', and then convert the BufferedImage to a PImage and send that to Spout after each frame is rendered.  

I fixed this by creating a subclass of PApplet called MApplet which initializes everything properly (for the most part). Once it's created, I call `PApplet.runSketch(new String[]{""}, applet);` where "applet" is the MApplet. This new MApplet is then passed into my Frame's constructor and stored. 

Inside of my MApplet, the Spout is created and initialized, and the only thing handled by my Frame is a call to applet.updateImage(BufferedImage iB), where it actually converts it to a PImage for the MApplet to draw on it's own time.

Since the main method handles the original instance of MApplet and its thread, it no longer causes conflict. 

The only thing not working so far is that my MApplet window starts off tiny and can only be maximized, but that is a question for a different place. 

Thank you for your help and your amazing work :)

**Comment by leadedge** [comment]
Sounds complicated.

The size problem might be solved if the sender size is linked directly to the image.

Instead of `SendTexture()`, try `SendTexture(img)`.
And in setup() use `setSenderName("MELTr") `instead of `createSender("MELTr")`

You might also need to add `updateSender(img.width, img.height)` after `img.updatePixels()` in `updateImage(BufferedImage bimg)`
